export const productValue = {
  max_confirmation_time: 'P0D',
  cutoff_time: 'P2D',
  booking_type: 'CALENDAR-TIMESLOTS',
  uuid: '0f608c73-2046-11e7-9cc9-06a7e332783f',
  city: {
    id: 2,
    name: 'Roma',
    country: {
      id: 82,
      name: 'Italia',
      iso_code: 'IT',
    },
    cover_image_url:
      'https://images.musement.com/cover/0002/37/top-view-of-rome-city-skyline-from-castel-sant-angelo-jpg_header-136539.jpeg',
    url: 'https://www.musement.com/it/roma/',
    time_zone: 'Europe/Rome',
  },
  saves: 0,
  title: 'Title',
  relevance: 10,
  emergency_phone_number: '(0039) 06 8336 0561',
  relevance_venue: 480,
  must_see: false,
  last_chance: false,
  top_seller: false,
  voucher_access_usage: 'MOBILE',
  temporary: false,
  description: 'Description',
  about: 'About',
  operational_days: 'Dal lunedì al sabato',
  duration: 'PT2H30M',
  duration_range: {
    max: 'PT2H30M',
  },
  validity: 'P0D',
  has_price_info_on_date: true,
  open: false,
  ticket_not_included: false,
  likely_to_sell_out: false,
  special_offer: false,
  exclusive: false,
  best_price: false,
  daily: false,
  languages: [
    { code: 'en', name: 'Inglese' },
    { code: 'fr', name: 'Francese' },
  ],
  group_size: [{ code: 'private', name: 'Tour privato' }],
  food: [],
  services: [{ code: 'dress-code', name: 'Dress Code' }],
  features: [
    { code: 'istant', name: 'CONFERMA ISTANTANEA' },
    { code: 'skip', name: 'SALTA LA CODA' },
  ],
  highlights: ['hight light 1', 'hight light 2'],
  included: ['included 1', 'included 2'],
  not_included: ['not included 1'],
  is_available_today: false,
  is_available_tomorrow: true,
  cover_image_url:
    'https://images.musement.com/cover/0001/19/vatican-museums-st-peter-s-and-sistine-chapel-tickets-and-skip-the-line-private-tour_header-18646.jpeg?w=540',
  service_fee: {
    currency: 'EUR',
    value: 0,
    formatted_value: '€ 0.00',
    formatted_iso_value: '0,00 €',
  },
  retail_price: {
    currency: 'EUR',
    value: 299,
    formatted_value: '€ 299.00',
    formatted_iso_value: '299,00 €',
  },
  retail_price_without_service_fee: {
    currency: 'EUR',
    value: 299,
    formatted_value: '€ 299.00',
    formatted_iso_value: '299,00 €',
  },
  original_retail_price_without_service_fee: {
    currency: 'EUR',
    value: 299,
    formatted_value: '€ 299.00',
    formatted_iso_value: '299,00 €',
  },
  original_retail_price: {
    currency: 'EUR',
    value: 299,
    formatted_value: '€ 299.00',
    formatted_iso_value: '299,00 €',
  },
  discount: 0,
  categories: [
    {
      id: 209,
      name: 'Attrazioni e tour guidati',
      level: '1',
      code: 'new-attractions-guided-tours',
      event_image_url:
        'https://images.musement.com/cover/0002/50/la-creazione-di-adamo-vaticani_header-149100.jpeg?w=540',
      cover_image_url:
        'https://images.musement.com/cover/0002/50/la-creazione-di-adamo-vaticani_header-149100.jpeg?w=540',
      url: 'https://www.musement.com/it/roma/attrazioni-e-tour-guidati-c/',
    },
  ],
  reviews_number: 17,
  reviews_avg: 4.6,
  reviews_aggregated_info: {
    1: 0,
    2: 0,
    3: 1,
    4: 4,
    5: 12,
  },
  latitude: 41.907,
  longitude: 12.453,
  url:
    'https://www.musement.com/it/roma/musei-vaticani-basilica-di-san-pietro-e-cappella-sistina-biglietti-e-visita-guidata-privata-salta-fila-864/',
  flavours: [
    {
      id: 113,
      name: 'Tour privato',
      active: true,
      slug: 'tour-privato',
    },
  ],
  verticals: [
    {
      id: 1,
      name: 'Arte e musei',
      active: true,
      code: 'arts-culture',
      slug: 'arte-e-musei',
      url: 'https://www.musement.com/it/arte-e-musei-t/',
      meta_title: 'Meta Title',
      meta_description: 'Meta Description',
      cover_image_url:
        'https://images.musement.com/vertical/0001/30/art-and-culture_header-29023.jpeg?w=540',
      relevance: 100,
    },
  ],
  giftable: true,
  has_passenger_info: false,
  has_extra_customer_data: false,
  buy_multiplier: 1,
  ticket: false,
  free_cancellation: true,
}
